config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    #
    namespace :admin do
        root to: 'dashboard#index'
        get :sign_in, to: 'session#new'
        post :login, to: 'session#login'
        delete :logout, to: 'session#logout'
        resources :articles
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < BaseController
    def index
    end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ::ApplicationController
    layout 'admin'
    class AdminResourceError < StandardError; end

    rescue_from AdminResourceError, with: :handle_auth_error

    def handle_auth_error err={}
        redirect_to admin_sign_in_url, notice: err.message
    end

    helper_method [:current_user]

    def current_user
        @user ||= User.find_by id: session[:user_id]
    end

    def signin params={}
        user = User.find_by_email params[:email]
        raise AdminResourceError, "邮箱找不到" unless user
        user = user.authenticate params[:password]
        raise AdminResourceError, "密码错误" unless user
        session[:user_id] = user.id
    end

    def logout
        session[:user_id] = nil
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
    def index
    end
end

app/controllers/admin/session_controller.rb
class Admin::SessionController < Admin::BaseController
    layout 'login'
    def new
        @user = User.new
    end

    def login
        signin session_params
        redirect_to admin_root_url, notice: "登录成功"
    end

    def logout
    end

    private

    def session_params
        params.fetch(:session, {}).permit(:email, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/admin/articles/index.html.erb
<h1>后台</h1>
<h2>文章管理页面</h2>

app/views/admin/dashboard/index.html.erb
<h2>后台管理员仪表盘主页</h2>

<% if current_user %>
    欢迎回来 email!: <%= current_user.email %>
<% end %>

app/views/admin/session/_form.html.erb
<div class="container">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">登录</h3>
            </div>
            <div class="panel-body">
                <%= form_with(model: user, url: admin_login_path, scope: :session) do |f| %>
                    <div class="form-group">
                        <%= f.label :email, "邮箱" %>
                        <%= f.text_field :email %>
                    </div>
                    <div class="form-group">
                        <%= f.label :password, "密码" %>
                        <%= f.password_field :password %>
                    </div>
                    <div class="form-group">
                        <%= f.submit '登录' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/session/new.html.erb
<%= render 'form', user: @user %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>管理员界面</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
        <h2><%= notice %></h2>
    <% end %>
    <div class="main">
        <div id="sidebar">
            <ul class="left-nav">
                <li><%= link_to '主页', '#' %></li>
                <li><%= link_to '新闻列表','#' %></li>
                <li><%= link_to '咨询列表','#' %></li>
            </ul>
        </div>
        <div class="my-container">
            <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBlogAuthentication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>登录界面</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if notice %>
        <h2><%= notice %></h2>
    <% end %>
    <%= yield %>
  </body>
</html>